### PR TITLE
fix: tets hang up

### PR DESCRIPTION
**Pull request by MaximoLiberata**
Fixes (https://github.com/mqttjs/MQTT.js/issues/1897#issuecomment-2231365999).

When you try to execute the tests maybe one of them will fail because it hanged up and never ends. This PR fix that bug in almost all cases.

### CODE REVIEW

**Comment by MaximoLiberata** [comment]
@robertsLando try to execute this PR many times and give me feedback if it working right, please.

**Comment by robertsLando** [comment]
Thanks for this PR @MaximoLiberata ! I hope you are right, unfortunately I will not be on my pc till Monday but I will definitely look at this ASAP! I checked the changes and it feels strange only this test was causing the issue, my feel was that there were many of them with this same problem. Did they always succeed now or they just fail less?

**Review by robertsLando — APPROVED** [review]
Thanks! 🙏🏼  LGTM

**Comment by robertsLando** [comment]
@MaximoLiberata Tests seems much more reliable now! Thanks again 🙏🏼

**Comment by MaximoLiberata** [comment]
I'm glad to hear! And thank you for checking 🙏🏼.

**Pull request merged**
