### PR TITLE
chore: replace `browserify` with `rollup`

### PR DESCRIPTION
**Pull request by robertsLando**

### CODE REVIEW

**Comment by robertsLando** [comment]
@vishnureddy17 @BertKleewein I made some changes here but I still get this error when i run the browser test:

`TypeError: (intermediate value).parser is not a function\n`

Seems that rollup output boundle makes some strange tweaks on [mqtt-packet](https://github.com/mqttjs/mqtt-packet/blob/master/parser.js#L10). In that line `this.constructor` is null and `this` points to `EventEmitter`, not `Parser` instance.

Couldn't find anything to fix this issue

**Comment by robertsLando** [comment]
Consider also replace terser with a rollup pluigin: https://rollupjs.org/configuration-options/#output-plugins

**Comment by vishnureddy17** [comment]
Unfortunately, my knowledge on browser JS and and bundling is very limited :/

**Comment by BertKleewein** [comment]
The `EventEmitter` problem happens because `require('events')` returns something that is both a constructor and a module. 

In other words, callers can choose to do either `const EventEmitter = require('events')` or they can do `const EventEmitter = require('events').EventEmitter`.  In node.js, these 2 methods are interchangeable.  In the browser, they're apparently not interchangeable.

One fix is to update the `mqtt-packet` module to use `require('events').EventEmitter`, assuming that this new syntax works on all not-ancient versions of node.js.

If you make this change to `mqtt-packet`, the next problem that pops up is where `readable-stream` uses `process.nextTick` and `process` is undefined. According to my rollup config, this _should_ have been polyfilled, but that's not happening for me.  I don't know why.

**Comment by robertsLando** [comment]
Thanks for the explanation @BertKleewein !

Anyway I also opened an [issue](https://github.com/rollup/rollup/issues/5062) on rollup yesterday and turns out that's a bug with rollup commonjs plugin... sad story this is my first time using rollup and I also found a bug, good news is that the user that answered my issue also created [this](https://github.com/rollup/plugins/pull/1537) PR to fix it. Hope it will not take too much time.

I will also try to see if I can fix the readable-stream issue

**Comment by robertsLando** [comment]
Ok some steps forward. I used @BertKleewein suggestion to fix the mqtt-packet parser issue, I firstly tried by using rollup `replace` plugin as I did later for readable-stream but without success so I manually patched the file. So now tests are starting but the output stucks on this point:

```
/MQTT.js$ npm run unit-test:browser

> mqtt@5.0.0-beta.2 unit-test:browser
> airtap --server test/browser/server.js test/browser/test.js

tunnelled server started on port 44229
TAP version 13
# MQTT.js browser test
client connect
ok 1 no error on subscribe
ok 2 no error on publish
ok 3 should match topic
ok 4 should match payload
```

Not sure if that's related to some compatibility issues with the `steam` module :(

**Comment by robertsLando** [comment]
With debug enabled: 

```
npm run unit-test:browser

> mqtt@5.0.0-beta.2 unit-test:browser
> airtap --server test/browser/server.js test/browser/test.js

tunnelled server started on port 42099
MqttClient :: options.protocol ws
MqttClient :: options.protocolVersion 3
MqttClient :: options.username null
MqttClient :: options.keepalive 60
MqttClient :: options.reconnectPeriod 1000
MqttClient :: options.rejectUnauthorized null
MqttClient :: options.properties.topicAliasMaximum null
MqttClient :: clientId mqttjs_857bf1ef
MqttClient :: setting up stream
_setupStream :: calling method to clear reconnect
_clearReconnect : clearing reconnect timer
_setupStream :: using streamBuilder provided to client to create stream
_setupStream :: pipe stream to writable stream
_setupStream: sending packet `connect`
sendPacket :: packet: { cmd: 'connect' }
sendPacket :: emitting `packetsend`
sendPacket :: writing to stream
sendPacket :: writeToStream result true
TAP version 13
# MQTT.js browser test
writable stream :: parsing buffer
work :: getting next packet in queue
work :: no packets in queue
work :: done flag is true
writable stream :: parsing buffer
work :: getting next packet in queue
work :: no packets in queue
work :: done flag is true
writable stream :: parsing buffer
work :: getting next packet in queue
work :: no packets in queue
work :: done flag is true
writable stream :: parsing buffer
parser :: on packet push to packets array.
work :: getting next packet in queue
work :: packet pulled from queue
_handlePacket :: emitting packetreceive
_handleConnack
_setupPingTimer :: keepalive 60 (seconds)
connect :: sending queued packets
deliver :: entry null
_resubscribe
client connect
subscribe: array topic hello
subscribe: pushing topic `hello` and qos `0` to subs list
subscribe :: resubscribe true
subscribe :: call _sendPacket
_sendPacket :: (mqttjs_857bf1ef) ::  start
sendPacket :: packet: {
  cmd: 'subscribe',
  subscriptions: [ { topic: 'hello', qos: 0 } ],
  qos: 1,
  retain: false,
  dup: false,
  messageId: 50292
}
sendPacket :: emitting `packetsend`
sendPacket :: writing to stream
sendPacket :: writeToStream result true
sendPacket :: invoking cb
nop :: null
writable stream :: parsing buffer
work :: getting next packet in queue
work :: no packets in queue
work :: done flag is true
writable stream :: parsing buffer
work :: getting next packet in queue
work :: no packets in queue
work :: done flag is true
writable stream :: parsing buffer
work :: getting next packet in queue
work :: no packets in queue
work :: done flag is true
writable stream :: parsing buffer
parser :: on packet push to packets array.
work :: getting next packet in queue
work :: packet pulled from queue
_handlePacket :: emitting packetreceive
_handleAck :: packet type suback
ok 1 no error on subscribe
publish :: message `Hello World!` to topic `hello`
publish :: qos 0
MqttClient:publish: packet cmd: publish
_sendPacket :: (mqttjs_857bf1ef) ::  start
sendPacket :: packet: {
  cmd: 'publish',
  topic: 'hello',
  payload: 'Hello World!',
  qos: 0,
  retain: false,
  messageId: 0,
  dup: false
}
sendPacket :: emitting `packetsend`
sendPacket :: writing to stream
sendPacket :: writeToStream result true
sendPacket :: invoking cb
ok 2 no error on publish
_sendPacket :: (mqttjs_857bf1ef) ::  end
writable stream :: parsing buffer
work :: getting next packet in queue
work :: no packets in queue
work :: done flag is true
writable stream :: parsing buffer
work :: getting next packet in queue
work :: no packets in queue
work :: done flag is true
writable stream :: parsing buffer
work :: getting next packet in queue
work :: no packets in queue
work :: done flag is true
writable stream :: parsing buffer
work :: getting next packet in queue
work :: no packets in queue
work :: done flag is true
writable stream :: parsing buffer
parser :: on packet push to packets array.
work :: getting next packet in queue
work :: packet pulled from queue
_handlePacket :: emitting packetreceive
_handlePublish: packet {
  cmd: 'publish',
  retain: false,
  qos: 0,
  dup: false,
  length: 19,
  topic: 'hello',
  payload: {
    type: 'Buffer',
    data: [
      72,
      101,
      108,
      108,
      111,
      32,
      87,
      111,
      114,
      108,
      100,
      33,
      [length]: 12
    ]
  }
}
_handlePublish: qos 0
ok 3 should match topic
ok 4 should match payload
end :: (mqttjs_857bf1ef)
end :: cb? true
_clearReconnect : clearing reconnect timer
end :: (mqttjs_857bf1ef) :: immediately calling finish
end :: (mqttjs_857bf1ef) :: finish :: calling _cleanUp with force false
_cleanUp :: done callback provided for on stream close
_cleanUp :: forced? false
_cleanUp :: (mqttjs_857bf1ef) :: call _sendPacket with disconnect packet
_sendPacket :: (mqttjs_857bf1ef) ::  start
sendPacket :: packet: { cmd: 'disconnect' }
sendPacket :: emitting `packetsend`
sendPacket :: writing to stream
sendPacket :: writeToStream result true
sendPacket :: invoking cb
_cleanUp :: clearing pingTimer
```

**Comment by BertKleewein** [comment]
@robertsLando - This looks like the same behavior I saw when patched mqtt-packet and readable-stream. Thanks for confirming that you see the same thing. It smells like it's maybe related to some of the `client.end` ugliness that I've been poking around. I'll take a look and see what I can find.

**Comment by robertsLando** [comment]
@BertKleewein I'm planning to do a PR that moves client pakcets handlers outside like aedes does: https://github.com/moscajs/aedes/tree/main/lib/handlers

Hope that will not be so hard BTW... My plans are to refactor client piece by piece without breaking too much stuff

**Comment by robertsLando** [comment]
Dunno if @mcollina could enlighten us on [this](https://github.com/mqttjs/MQTT.js/pull/1632#issuecomment-1633777570), I'm not sure it's only a problem with MQTTjs, maybe it's something related to the readable-stream changed with `stream` or the `setImmediate` behaving different in browser env

**Comment by robertsLando** [comment]
@getlarge ever used rollup ? :) I'm a bit lost here

**Comment by getlarge** [comment]
> @getlarge ever used rollup ? :) I'm a bit lost here

Never did sorry! Still stuck ?

**Comment by robertsLando** [comment]
Supersided by #1658

**Pull request closed without merging**
