### PR TITLE
Bumped websocket-stream to 2.0.2 and others.

### PR DESCRIPTION
**Pull request by mcollina**
This adds a clean install for iojs v3, too.

@psorowka @sahilsk and everybody, please check :)

### CODE REVIEW

**Comment by psorowka** [comment]
Build looks good. But check-style seems to require a lot of work...

**Comment by sahilsk** [comment]
same here. 
eslint rules has gotten deprecated and removed/renamed some rules. after fixing them i'm now getting identiation errors.  I tried `fixmyjs` and `js-beautifier` but they triggered more errors.

other than that  test are working find on latest iojs(v3) and node(0.12).

@mcollina  any quick way to fix this identation?

image

**Comment by psorowka** [comment]
I could reduce the errors to 60 by configuration, mainly the `SwitchCase` Option in `indent` and the `Markers` in `spaced-comment` . Remaining errors are mostly from space-comment (from things like: `function (/*error*/)` and indentation from `var` declaration. 

````
     "no-underscore-dangle": [
-      0,
-      false
+      0
     ],
     "yoda": [
       1,
@@ -23,7 +22,8 @@
     ],
     "indent": [
       2,
-      2
+      2, 
+      {"SwitchCase": 1}
     ],
     "brace-style": [
       2,
@@ -43,7 +43,7 @@
     "no-nested-ternary": 2,
     "no-undefined": 2,
     "radix": 2,
-    "space-after-function-name": [
+    "space-before-function-paren": [
       1,
       "always"
     ],
@@ -52,12 +52,17 @@
       "always"
     ],
     "space-before-blocks": 2,
-    "spaced-line-comment": [
+    "spaced-comment": [
       2,
       "always",
       {
         "exceptions": [
           "-"
+        ],
+        "markers": [
+          "eslint", 
+          "jshint",
+          "global"
         ]
````

**Comment by itavy** [comment]
hi,

after i made all the above changes in eslint, all the remaining errors are valid complaints regarding the rules defined. indeed eslint library has made some breaking changes at 0.9 version but all of them can be replaces as is stated above.

most of the errors about comment spacing, can be solved by deleting the comments. i put them when i made the styling changes to show that there you receive a parameter but is your decision to not use it; 

as for the indent spacing error, those need to be solved by spacing according to rules.

i did a new branch with all the changes so you can merge it into this one:
[bumped-depdencies-eslint](https://github.com/mqttjs/MQTT.js/tree/bumped-depdencies-eslint)

**Comment by psorowka** [comment]
:+1:

**Comment by mcollina** [comment]
Thanks @itavy! I've merged your commit into this PR. If it's all good, then we can release 1.4.0.

**Comment by psorowka** [comment]
looks good from my side. go for it. ponte is the next candidate for iojsv3 :)

**Comment by psorowka** [comment]
:+1: can you leave me a note when you have published to npm?

**Comment by mcollina** [comment]
Done

**Pull request merged**
