### PR TITLE
fix: edge case when handlePacket is called after .end()

### PR DESCRIPTION
**Pull request by mvayngrib**

### CODE REVIEW

**Comment by mcollina** [comment]
Can you please add a unit test for this case?

**Comment by mvayngrib** [comment]
@mcollina i've updated the PR with a unit test 

however, i noticed that other functionality relies on `_handlePacket` being called while `disconnecting` is true, e.g. this test: "should delay ending up until all inflight messages are delivered"

the original reason for this fix is that i was getting a `puback` when `outgoingStore` was already set to null. How would you prefer to handle this?

**Comment by mcollina** [comment]
I'm a bit lost.
I'd like to retain the current functionality. We might want to delay clearing up the stores until all messages are delivered, if I understand your goal correctly.

**Comment by mvayngrib** [comment]
haha, i'm sure i'm more lost. Basically, in some edge cases, `outgoingStore` is null and `outgoingStore.del` errors

**Comment by mcollina** [comment]
Can you please add a unit test that verifies one of those edge cases?

**Comment by mvayngrib** [comment]
@mcollina not actually sure what causes it, but i'll look out for a repro. Just fyi, i'm using `mqtt@1.11.2` by way of `aws-iot-device-sdk`

**Comment by robertsLando** [comment]
If you wish to continue with this PR please remember to change destination branch from `master` to `main` 🙏🏼

**Comment by robertsLando** [comment]
@mvayngrib could I know if you closed this because it wasn't fixing the issue or because you are not interested in continue with the PR?

**Comment by mvayngrib** [comment]
@robertsLando i won't have time to pursue this in the foreseeable future 😅. It also doesn't seem like this is an issue for anyone else, so maybe it's fine as is

**Comment by robertsLando** [comment]
I prefer to keep this open as it could be a  fix to some edge case issues

**Comment by robertsLando** [comment]
Supersided by #1780

**Pull request closed without merging**
