### PR TITLE
[WIP]Add basic compile/connect/sub/pub TypeScript test

### PR DESCRIPTION
**Pull request by sublimator**

### CODE REVIEW

**Comment by mcollina** [comment]
This is actually quite nice. Is this ready to go?

**Comment by yohei1126** [comment]
we should have tests for Typescript definitions.

**Comment by sublimator** [comment]
Yohei, what do you mean ?

**Comment by yohei1126** [comment]
This is still WIP and not merged. I think we should have tests for the
definitions in the CI.
2017年7月13日(木) 13:06 sublimator <notifications@github.com>:

**Comment by sublimator** [comment]
I can fix up the merge conflicts and add it to the CI I guess ... we can always revisit it. It's better than nothing right ?

**Comment by sublimator** [comment]
I'm merging this, as it doesn't touch any actual code so it's safe to do so. We can improve it later

**Comment by sublimator** [comment]
@yohei1126 

Feel free to improve/add/etc of course!

**Comment by yohei1126** [comment]
thanks!
2017年7月13日(木) 13:59 sublimator <notifications@github.com>:

**Pull request merged**
