### PR TITLE
server rotation fix

### PR DESCRIPTION
**Pull request by piotrmach**

### CODE REVIEW

**Comment by mcollina** [comment]
Anybody wants to clean this up, review it, add a test?

**Comment by mcollina** [comment]
This looks good, would you mind adding a test for this?

**Comment by piotrmach** [comment]
Ok now it tests it.
I changed existing test, it was checking it client reconnect to second server, but wasnt checking hostname param

**Comment by mcollina** [comment]
Thanks! released as 1.7.1

**Pull request merged**
