### PR TITLE
bump websocket-stream to 3.0.1 for nsp fix

### PR DESCRIPTION
**Pull request by ralphtheninja**
mqtt-nsp

### CODE REVIEW

**Comment by mcollina** [comment]
Yeah, I know of this particular issue :).
I didn't fix/release it before now because we are not affected by that specific bug (we are validating that we are __always__ sending a `Buffer`). Also websocket-stream changes a bit in v3, as it becomes an object mode stream.

But you are right that we need to get this fixed and release asap, just to please nsp.

**Comment by ralphtheninja** [comment]
> we are validating that we are always sending a Buffer

Aah cool. That's good to know! So my projects using `mqtt.js` can ignore nsp on this particular issue.

**Comment by mcollina** [comment]
Released as 1.7.0.

**Comment by ralphtheninja** [comment]
> Released as 1.7.0.

Rock n roll. Thanks Matteo!

**Pull request merged**
