### PR TITLE
Missing done check in _cleanUp

### PR DESCRIPTION
**Pull request by gautaz**
Here is the PR to fix the issue found here declared in this [comment](https://github.com/mqttjs/MQTT.js/issues/767#issuecomment-365211728).

I have also added a non regression test for this particular case.
Sorry for the mistake, my bad.

### CODE REVIEW

**Comment by gautaz** [comment]
Wow, that's strange, my modification has nothing to do with QOS.
@mcollina Any idea on what happened ?

**Comment by mcollina** [comment]
I think it's just the CI that is flaky.

**Comment by gautaz** [comment]
OK, I'll close and reopen the pull request just to restart the build.

**Comment by mcollina** [comment]
@gautaz this seems to be breaking Node v4.3.2, which we still support because of AWS Lambda.

**Comment by gautaz** [comment]
OK, I will try to reproduce in a Docker environment with node v4.3.2.
I'll keep you posted.

**Comment by gautaz** [comment]
@mcollina I have tried to reproduce multiple times with [nodesource/wily:4.3.2](https://hub.docker.com/r/nodesource/wily/) but I did not succeed.

In the meantime all tests pass now on Travis. I guess I'll have to find a slower platform to reproduce.
Do you still want to hold on this issue or is it OK for now ?

**Pull request merged**
