### PR TITLE
add a function to get last id

### LINKED ISSUE #525: How to get message id
In my project, I need a way to get packet id for each packet because of the following situation.
Can I get a packet id for each packet?

* Some MQTT broker respond result of client's action asuch as publish/subscribe to special topic.
* The broker usually send packet id that is sent by the client so that the client can check result for each packet.

* Because of the above situation, the client save pakcet id locally so that the client can check result later.
* When the client receives result of the action from the broker, the client match packet id from the broker and packet id saved locally to check which actions is successful or not.

### PR DESCRIPTION
**Pull request by yohei1126**
fixes #525

### CODE REVIEW

**Comment by mcollina** [comment]
Awesome! Can you add it to the README as well?

**Comment by yohei1126** [comment]
@mcollina add the description for the function. please check it.

**Comment by mcollina** [comment]
@yohei1126 while reviewing, it seems better to have `getLastMessageId()`  instead of `getLastId()`,  as it is not super clear in the docs.

Also, you should mention this is for sent messages only.

**Comment by yohei1126** [comment]
please check it.

**Comment by ogis-onishi** [comment]
The following type definiton for TypeScript need to be updated. I wll send pq as well. 
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/mqtt/index.d.ts

**Comment by yohei1126** [comment]
The following type definiton for TypeScript need to be updated. I wll send pq as well.
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/mqtt/index.d.ts

**Comment by yohei1126** [comment]
sending pq now. https://github.com/DefinitelyTyped/DefinitelyTyped/pull/14179

**Comment by yohei1126** [comment]
The pull request is approved. https://github.com/DefinitelyTyped/DefinitelyTyped/pull/14179#pullrequestreview-17859178

Waiting for the npm module @types/mqtt get updated.

**Pull request merged**
