### PR TITLE
feat: react-native support

### PR DESCRIPTION
**Pull request by rrebase**
Add support for React Native by leveraging the `react-native` entrypoint (metro bundler makes use of it), extending the browser behaviour and polyfilling anything that still broke

This does introduce a [tiny](https://bundlephobia.com/package/safe-buffer@5.2.1) package `safe-buffer` to dependencies, which NodeJS doesn't need.

Resolves https://github.com/mqttjs/MQTT.js/issues/1264, https://github.com/mqttjs/MQTT.js/issues/573

### CODE REVIEW

**Comment by umangloria** [comment]
@rrebase  I tried your branch to get it working on RN but getting this error related to 'net' package. 
Simulator Screen Shot - iPhone 14 - 2023-03-28 at 23 10 33

**Comment by rrebase** [comment]
@umangloria it seems that the shims were not applied (bundler didn't use the `react-native` entry point) 🤔

What version of RN do you have there, is it using the metro bundler?

**Comment by umangloria** [comment]
> @umangloria it seems that the shims were not applied (bundler didn't use the `react-native` entry point) 🤔
> 
> What version of RN do you have there, is it using the metro bundler?

@rrebase  I just created a fresh project by `npx react native init MqttDemo` so it the latest version. Strange enough, I got stuck at this `stream.pipe(` crash. I am out of ideas as I already tried installing that stream package directly in project's `package.json` file. But no luck 😕

**Comment by umangloria** [comment]
I looked further into this and I think it is because on react-native it is not able to find `net` module. I think if it is react native then we should be using `react-native-tcp-socket`. I am not sure how to do that as every time it tries to look for net package from the node.

**Comment by robertsLando** [comment]
@rrebase @umangloria anyone that would like to finish this?

**Comment by garzfaust** [comment]
This version does not work. It is missing the NPM package `url`. When you install it with `npm install url`, it does.

*Attention 1:* The drawback of using MQTT.js in React Native is, that it can only send via WebSocket, but noch via plain TCP. Thus your MQTT broker needs to support WebSocket.

*Attention 2:*: MQTT.js is swallowing errors! If the error number is not known to MQTT.js, it does not emit the error event, thus you will never realise that there was an error using `client.on('error', ...)`. I had the situation, that it would not connect to the broker, without reporting any errors. I had to debug through the MQTT.js code to find out, that there was an error indeed, but it was swallowed. I would doubt that this is good library design. If a error number is undefined, you might report an unknown error number. Reporting no error at all for sure is not good.

### Here are instructions on how to get the React Native supported fork working

At first, install the branch `react-native-layer` of this MQTT.js fork: https://github.com/rrebase/MQTT.js/tree/react-native-layer

`npm install git+https://github.com/rrebase/MQTT.js.git#react-native-layer`

Then install the missing `url` package.

`npm install url`

*Note:* Instead of installing the `url` package, it is also possible to work with this solution here instead: https://github.com/parshap/node-libs-react-native

**Pull request closed without merging**
