### PR TITLE
fix: prevent url.parse to set `path` option

### LINKED ISSUE #1870: [Bug]: IPV6 connectivity broke in 5.5.4
### MQTTjs Version

5.5.4

### Broker

mosquitto

### Environment

NodeJS

### Description

MQTT.js confuses ipv6 address with UNIX socket.

Was discovered in zigbee2mqtt https://github.com/Koenkk/zigbee2mqtt/issues/22390

### Minimal Reproduction

1. Start mosquitto and make sure it listens on ipv6 endpoint (it does in default installation in OpenSUSE):
```
1716396210: Opening ipv4 listen socket on port 1883.
1716396210: Opening ipv6 listen socket on port 1883.
1716396210: mosquitto version 2.0.18 running
```

2. The sample from README.md, just with changed host to ::1 (localhost)

```
const mqtt = require("mqtt");
const client = mqtt.connect("mqtt://[::1]");

client.on("connect", () => {
    client.subscribe("presence", (err) => {
        if (!err) {
            client.publish("presence", "Hello mqtt");
        }
    });
});

client.on("message", (topic, message) => {
    // message is Buffer
    console.log(message.toString());
    client.end();
});
```

3. Try 5.5.3 - works, creates `AF_INET6` socket:
```
$ npm install mqtt@5.5.3

$ strace -e trace=%net node test.js 
socket(AF_INET6, SOCK_STREAM|SOCK_CLOEXEC|SOCK_NONBLOCK, IPPROTO_IP) = 20
connect(20, {sa_family=AF_INET6, sin6_port=htons(1883), sin6_flowinfo=htonl(0), inet_pton(AF_INET6, "::1", &sin6_addr), sin6_scope_id=0}, 28) = -1 EINPROGRESS (Operation now in progress)
getsockopt(20, SOL_SOCKET, SO_ERROR, [0], [4]) = 0
Hello mqtt
shutdown(20, SHUT_WR)                   = 0
+++ exited with 0 +++
```

4. Try 5.5.4 - tries `AF_UNIX` and fails:
```
$ npm install mqtt@5.5.4
$  strace -e trace=%net node test.js 
socket(AF_UNIX, SOCK_STREAM|SOCK_CLOEXEC|SOCK_NONBLOCK, 0) = 19
connect(19, {sa_family=AF_UNIX, sun_path="/"}, 110) = -1 EACCES (Permission denied)
socket(AF_UNIX, SOCK_STREAM|SOCK_CLOEXEC|SOCK_NONBLOCK, 0) = 19
connect(19, {sa_family=AF_UNIX, sun_path="/"}, 110) = -1 EACCES (Permission denied)
socket(AF_UNIX, SOCK_STREAM|SOCK_CLOEXEC|SOCK_NONBLOCK, 0) = 19
connect(19, {sa_family=AF_UNIX, sun_path="/"}, 110) = -1 EACCES (Permission denied)
```

### Debug logs

```
$ env DEBUG=mqttjs* node test.js 
  mqttjs connecting to an MQTT broker... +0ms
  mqttjs:client MqttClient :: version: 5.5.4 +0ms
  mqttjs:client MqttClient :: environment node +0ms
  mqttjs:client MqttClient :: options.protocol mqtt +0ms
  mqttjs:client MqttClient :: options.protocolVersion 4 +0ms
  mqttjs:client MqttClient :: options.username undefined +0ms
  mqttjs:client MqttClient :: options.keepalive 60 +0ms
  mqttjs:client MqttClient :: options.reconnectPeriod 1000 +0ms
  mqttjs:client MqttClient :: options.rejectUnauthorized undefined +0ms
  mqttjs:client MqttClient :: options.properties.topicAliasMaximum undefined +0ms
  mqttjs:client MqttClient :: clientId mqttjs_56f3a523 +0ms
  mqttjs:client MqttClient :: setting up stream +0ms
  mqttjs:client connect :: calling method to clear reconnect +1ms
  mqttjs:client _clearReconnect : clearing reconnect timer +0ms
  mqttjs:client connect :: using streamBuilder provided to client to create stream +0ms
  mqttjs calling streambuilder for mqtt +2ms
  mqttjs:tcp port 1883 and host ::1 +0ms
  mqttjs:client connect :: pipe stream to writable stream +0ms
  mqttjs:client connect: sending packet `connect` +1ms
  mqttjs:client _writePacket :: packet: {
  mqttjs:client   cmd: 'connect',
  mqttjs:client   protocolId: 'MQTT',
  mqttjs:client   protocolVersion: 4,
  mqttjs:client   clean: true,
  mqttjs:client   clientId: 'mqttjs_56f3a523',
  mqttjs:client   keepalive: 60,
  mqttjs:client   username: undefined,
  mqttjs:client   password: undefined,
  mqttjs:client   properties: undefined
  mqttjs:client } +0ms
  mqttjs:client _writePacket :: emitting `packetsend` +0ms
  mqttjs:client _writePacket :: writing to stream +0ms
  mqttjs:client _writePacket :: writeToStream result true +10ms
  mqttjs:client streamErrorHandler :: error connect EACCES / +1ms
  mqttjs:client streamErrorHandler :: emitting error +0ms
  mqttjs:client (mqttjs_56f3a523)stream :: on close +1ms
  mqttjs:client _flushVolatile :: deleting volatile messages from the queue and setting their callbacks as error function +0ms
  mqttjs:client stream: emit close to MqttClient +0ms
  mqttjs:client close :: connected set to `false` +0ms
  mqttjs:client close :: clearing connackTimer +0ms
  mqttjs:client close :: destroy ping timer +0ms
  mqttjs:client close :: calling _setupReconnect +0ms
  mqttjs:client _setupReconnect :: emit `offline` state +0ms
  mqttjs:client _setupReconnect :: set `reconnecting` to `true` +0ms
  mqttjs:client _setupReconnect :: setting reconnectTimer for 1000 ms +0ms
```

### PR DESCRIPTION
**Pull request by robertsLando**
Fixes #1870

### CODE REVIEW

**Comment by robertsLando** [comment]
Could you give a try to this please @ytimenkov?

**Comment by robertsLando** [comment]
I think we need some better tests for this so, since I jump in maintaining this repo I find out the coverage is not that good as each release easily breaks something even if tests are passing 😅 I'm sorry for that and I will fix that tomorrow, feel free to open a PR if you can as the fix is not that hard (just look at my changes here and add the path to options when protocol i ws/wss and a test of course ;))

**Comment by ytimenkov** [comment]
Yeah... Took me like half an hour to understand how this simple fix added support for unix sockets and how it broke them...

It feels that we mixed 2 different OSI layers: for WebSockets, path is part of application layer (7) while for UNIX it's network address => probably as low as layer 3.

I don't see any good way to disambiguate the grammar except for explicitly state address family (inet(6) vs unix).

Either as git does (git+https) or as a stand-alone option (like curl's `--unix-socket`). Strictly speaking, you may have WebSocket connection over Unix socket 🤷‍♂️. (However I'm not sure how in this case separate socket path from address..., except for curl's option).

I also think that it is strange that url parsing library which you use yields `/` path for ipv6 address and `undefined` for ipv4.

**Comment by robertsLando** [comment]
@ytimenkov I think it could make sense to add an option on mqtt client to explicitly say when you want to connect to a unix socket ot not, like `isUnixSocket` so this would be much more easy to handle.

I have drafted a PR here: https://github.com/mqttjs/MQTT.js/pull/1874

But that's without that option, I would like to know your opinion about the new option and if we agree I can add that

**Pull request merged**
