### PR TITLE
docs: react native example

### PR DESCRIPTION
**Pull request by MaximoLiberata**

### CODE REVIEW

**Review by robertsLando — CHANGES_REQUESTED** [review]
Could you also update the TOC? There should be an action on vscode to do that automatically

**Comment by MaximoLiberata** [comment]
> Could you also update the TOC? There should be an action on vscode to do that automatically

Could you explain me a little more about that? I don't know how i can do that

**Comment by robertsLando** [comment]
You can do it manually or use this vscode plugin named "Markdown all in one":

**Comment by MaximoLiberata** [comment]
I updated the TOC

**Review by robertsLando — APPROVED** [review]

**Pull request merged**
