### PR TITLE
feat: option to disable `writeCache` and fix leak in subscriptions

### PR DESCRIPTION
**Pull request by robertsLando**
Move commits from master

### CODE REVIEW

**Comment by robertsLando** [comment]
@vishnureddy17 I dunno if there are other cleaner ways to do this, I found some old PR that I merged were pointing to master, I noticed this just now and with this commit I'm moving them to main (squash).

**Comment by vishnureddy17** [comment]
I don't think we should squash this one.

**Review by vishnureddy17 — APPROVED** [review]

**Comment by robertsLando** [comment]
@vishnureddy17 I enabled rebase but GH tells me there are conflicts (even if this pr is even with main branch)

**Comment by vishnureddy17** [comment]
In that case, could we squash merge but make sure that the titles of the underlying commits (including the PR numbers) are in the commit description? That way someone can still go through the commit history and find the relevant PRs in the future.

Once we are sure that everything is in main and master doesn't have anything important, I think we should delete master to avoid future confusion.

This is probably really annoying, I really appreciate your handling this :)

**Comment by robertsLando** [comment]
Sure! No problem, I understand that :) I will do it on Monday

**Comment by robertsLando** [comment]
@vishnureddy17 agree about the lock, not sure about deleting it. I would keep it for now, anyway PR merge should fail right now. Not sure if there is an easier way to move all open PR from master to main, maybe someone ha built a tool for that?

**Pull request merged**
