### PR TITLE
feat: add support for files/unix sockets

### LINKED ISSUE #1040: Connect to unix socket
Would you consider support for connecting to unix sockets? The use case is a local application wanting to connect to a local MQTT broker without having to create a network.

It looks like `lib/connect/unix.js` would be very similar to `tcp.js`, but with this sort of construct instead:

```
    unixpath = '/var/run/mqtt.socket'

    return net.createConnection(unixpath)
```

### PR DESCRIPTION
**Pull request by ralight**
Closes #1040.

### CODE REVIEW

**Comment by ralight** [comment]
Sure thing, could you give me a hint on where to start?

**Comment by YoDaMa** [comment]
https://github.com/mqttjs/MQTT.js/blob/master/test/client.js is the tests for the regular MQTT.js client, and you'll note this test extends the abstact_client.js tests. Following this model but for the specific connection type should be the best option. Instead of a regular HTTPServer though you'll need something specific for the Unix Domain Socket.

**Comment by robertsLando** [comment]
@ralight Could you add the required tests please?

**Comment by robertsLando** [comment]
also please move the PR to main instead of master

**Comment by robertsLando** [comment]
This is already possible with standard `mqtt` protocol by using `path` in client options

**Pull request closed without merging**
