### PR TITLE
[#682] Fix bug with reschedulePing causing a dropped connection to ne…

### PR DESCRIPTION
**Pull request by duncanfinney**
…ver be realized

### CODE REVIEW

**Comment by duncanfinney** [comment]
Fixes #682

**Comment by mcollina** [comment]
I am 👎  with this change as is.

The spec reports:

> If a Client does not receive a PINGRESP Packet within a reasonable amount of time after it has sent a PINGREQ, it SHOULD close the Network Connection to the Server. (Section 3.1.2.10 - Keep Alive).

So, we should schedule the PINGRESP to be checked not at any given interval, but rather after a reasonable amount of time after a PINGREQ has been set.

**Comment by duncanfinney** [comment]
I actually read the same thing with a college from work today and we came to a similar conclusion. We also thought the wording was a little vague.

This is what it is saying right? 

```
Whenever any control packet (including pingresp) arrives from the server:
   - reschedule _performServerPingCheck() at T=current_time + keepalive
```
    
```
function _performServerPingCheck() {
     sendAPing()
     setTimeout(() => {
        if (haven'tGottenAPingSinceISentIt()) { closeConnection() }
    }, opts.pingRTTMaximumMillis); 
}
```

We didn't know how to word the configuration or what the default value should be. What would be "a reasonable amount of time"? I was thinking 5 seconds.

**Comment by mcollina** [comment]
My original implementation was: if you didn't receive one before sending the next one, then it's probably time to drop. I don't see what is wrong with that, and how it can cause problems (the code might, the principle seems sound).

**Comment by duncanfinney** [comment]
It doesn't cause problems if reschedulePings is turned off. 

But if you have it set to true, anytime you publish a message it moves the check farther into the future (even when the broker has torn down the connection on the other end). 

https://github.com/mqttjs/MQTT.js/blob/master/lib/client.js#L728

Since we publish messages faster than the keepalive period always, we never would hit `_checkPing()`

**Comment by mcollina** [comment]
the timer is shifted only if the client is connected, as https://github.com/mqttjs/MQTT.js/blob/master/lib/client.js#L711 dictates. 

The goal is to never hit `_checkPing()`, that's the point. If we are sending data and the connection has not been severed, we should not send, receive or check PINGREQ and PINGRESP.

**Comment by duncanfinney** [comment]
That was the thing. The MQTT client isn't aware that the connection has been severed by the server because it was disconnected. It waits for the TCP to timeout which seems to be a really long time. 

There might be something wrong with the TCP settings... this is on a Linux Yocto build.

**Comment by mcollina** [comment]
Have you tried setting the timeout on the socket itself with https://nodejs.org/api/net.html#net_socket_settimeout_timeout_callback?

Maybe we should provide that as option, or maybe set it automatically a 2x keepAlive.

**Comment by arihantdaga** [comment]
Any news on this ??

**Comment by mcollina** [comment]
This PR can be closed.
I think the suggestion in https://github.com/mqttjs/MQTT.js/pull/683#issuecomment-330186022 still holds.

**Pull request closed without merging**
