### PR TITLE
Disabled auto reconnect for wrong credentials

### PR DESCRIPTION
**Pull request by diegovasquesmellet**
This PR is basically to disable the auto reconnect if the user typed wrong credentials (errors 4 / 5)

### CODE REVIEW

**Comment by diegovasquesmellet** [comment]
Hey..
I think it would look good.

Will work on it.

**Comment by diegovasquesmellet** [comment]
We are sending the error like this: `var err = new Error('Connection refused: ' + errors[rc])`
Do you want to create an specific one for wrong credentials? They way it is we are already sending a connection refused + error.

**Comment by atrovato** [comment]
Hello,
on my side, when MQTT could not connect, it retries... but I never get any error.

**Comment by diegovasquesmellet** [comment]
This is funny. It was supposed to emit a connection refused error.

**Comment by quaddan** [comment]
Is there any news?

**Pull request closed without merging**
