### PR TITLE
v2 dev

### LINKED ISSUE #166: Restore subscribtions after reconnect in deferred open scenario
Hi,
   I am using MQTT(client ) and Mosquitto(broker). I have clients which will be subscribed to the broker always. If the the broker restarts or goes down the client is not able to re-connect or throw any error. Is this also related to #112 and #148. I am using mqtt 0.3.8. My client is created as
client = mqtt.createClient(PORT,MQTT_SERVER, { encoding : 'binary', username : MQTT_USERNAME, password : MQTT_PASSWORD, clientId : 'backend'});

### LINKED ISSUE #348: mqtt.js 1.5.0 CLI get stuck
This is just something I would like to point out.

Running this command, the mqtt.js CLI 'freezes' with no response:

     mqtt publish -h '192.168.1.12' -t 'anyone' -m 'hello world' -u 'megatron' -p 'ciao123'

Because mistakenly using the lower case -p instead of -P to specify the password (mqtt.js acts as 'ciao123' was the port number..).

I don't know if this is worth a 'fix', but can't be useful some kind of hint/error in this scenario?

### LINKED ISSUE #382: Default value of keepalive should be at least 1 minute
As title: any opinions?

### LINKED ISSUE #431: Connection is broken query
Hi,

I am looking at understanding the capability of mqtt.js a little more when a clients connection to a broker is broken.

I've read through the documentation and I am still a little unsure what happens to outgoing messages when the client fails to connect, are messages automatically queued as default or do I need to set something explicitly to enable this queuing. I can see that QoS: 0 is default, and therefore should queue QoS zero messages?

Is there a limit to what can be queued, is it stored in memory or written to disk?

Is there a way to log what has been written to the queue and when it is removed from the queue when the connection is re-established?

Thank you in advance!

Jon

### PR DESCRIPTION
**Pull request by mcollina**
This PR is up for discussion to release a new major version of MQTT.js.
Thanks to the update to mqtt-packet v4, it's 3x faster in sending packets.

* [x] Update to [mqtt-packet](http://npm.im/mqtt-packet) v4
* [x] Drop support for node v0.8 and v0.10.
* [x] Drop deprecated API, in particular `createClient`, `createServer` and so on
* [x] Use [readable-stream](http://npm.im/readable-stream) v2.x.x

Please review my changes :).

Fixes #382.
Fixes #351.
Fixes #431.
Fixes #348.
Fixes #166.

Standardized, hurray!

### CODE REVIEW

**Comment by mcollina** [comment]
@jdiamond, would you like to have a look at #343, #344 and #166. These should be along the lines of what you have contributed recently.

**Comment by mcollina** [comment]
@jdiamond would you mind testing/reviewing this?

**Comment by ralphtheninja** [comment]
@mcollina When v2 is released, mind writing something about what has changed api wise?

**Comment by wuhkuh** [comment]
These commits still utilize util.inherits which is deprecated and discouraged (see #458) - would a change be possible before this one gets pulled?

**Comment by mcollina** [comment]
Please, send a PR against this branch that replaces them with the inherits module.

**Comment by roccomuso** [comment]
@wuhkuh @mcollina but shouldn't be kept somehow the backwards compatibility with older node.js versions? those not ES6-compliant..

**Comment by itavy** [comment]
that can be solved very easy with babel. transpile it to use at least 0.12.

**Comment by mcollina** [comment]
@roccomuso what do you mean? We bump the dependency not because of ES6, but because of streams 3, and the complexities of keeping the codebase in shape for that. v1 is still there to use, and if we want to backport patches, we can! Would you like to take care of the v1.x.x of MQTT.js?

**Comment by roccomuso** [comment]
@mcollina I'm referring to the usage of <code>util.inherits()</code> that is discouraged but required for older node.js version, that's why @itavy proposed the use of babel.

**Comment by wuhkuh** [comment]
@roccomuso Aren't we dropping support for older node.js versions?

> Drop support for node v0.8 and v0.10.

**Comment by mcollina** [comment]
@roccomuso we are not using any ES6 for inhering. Giving that `util.inherits` its discouraged, we switched to the npm module http://npm.im/inherits

**Comment by roccomuso** [comment]
@mcollina uh great then. Now I realized what you meant with **replaces them with the inherits module.** ;)

**Pull request merged**
