### PR TITLE
allow to publish binary message

### PR DESCRIPTION
**Pull request by shankerwangmiao**

### CODE REVIEW

**Comment by RalphL79** [comment]
Is there any change for the MQTT protocol (server and client side) allow by default hexadecimal values. I say this because for interfacing and interacting with a microcontroller based application (SAMD21/WINC1500/MSP430/Arduino or other), it is much more interesting than the UTF8 encoding. It would be very fancy if the publish function could receive by argument an Array (or Buffer or other) of hexadecimal (8 bits - 1 byte) values. With this, the MQTT could act as an broker/bridge between several platforms, for instance between:
- an server (service) based application, which is continuously working;
- an webpage client based in websockets (or others), for interface and user friendly web page application, this client will only be open when the user needs.
- an external client, with a microcontroller based application which is continuously working and connecting and reconnecting whenever is needed (eventually if there is an wifi/internet connection failure).
I say this because, I'm digging and searching a lot and until now I didn't find a good way of doing this...

**Comment by shankerwangmiao** [comment]
@RalphL79 As shown in [section 3.3.3](http://docs.oasis-open.org/mqtt/mqtt/v3.1.1/errata01/os/mqtt-v3.1.1-errata01-os-complete.html#_Toc442180853) of the MQTT standard, the payload of a published message is not necessarily a utf-8 string, and can be any type of binary data instead.

For me, I'm using mosca to act as a broker, with an interface where I can directly sub/pub binary messages. On embedded platforms, I recommend [paho](https://github.com/eclipse/paho.mqtt.embedded-c). For parsing and serializing structured data, you can try protobuf.

**Comment by RalphL79** [comment]
@shankerwangmiao, in fact the MQTT in the server receives the hex (8bit) data array from the client based microcontroller, but when I want to send again the same payload from the server to the client, the MQTT publish function parses the hex data for example 0x05 has 0x30, 0x35, so I sent in the server 0x05 (one byte) and

**Comment by RalphL79** [comment]
... I receive in the micro 0x30 and 0x35  (two bytes)...

**Comment by shankerwangmiao** [comment]
@RalphL79 How did you send that payload? Can you show some code?

**Comment by RalphL79** [comment]
@shankerwangmiao  the payload is something like this:
var host = 'wss:/mqtt.server:8085'; // our internal server
var options = {
	cmd: 'connect',	
	protocolId: 'MQTT',
	protocolVersion: 4,
	clientId: clientId,
	encoding: 'hex',
	username: 'user_name',
	password: 'pss3rd',
	will: 
	{
		topic: 'test/',
		payload: 'Connection Closed abnormally..!'
	},
}
var client = mqtt.connect(host, options);
client.on("message", function (topic, message) 
{
	const buffer = new Uint8Array([ 0x01, 0x05, 0x45, 0x8B, x9A]).buffer;
	payload = buf2hex(buffer);
	client.publish(topic, payload);
}
If we send the payload as string, the message is sent, however if we send the payload as array, the server (or the broker) disconnects and the message is not sent. All MQTT connections are closed in the port and the connection is restarted by itself.

**Comment by shankerwangmiao** [comment]
How about 

```
const buffer = new Buffer.from([ 0x01, 0x05, 0x45, 0x8B, 0x9A]);
client.publish(topic, buffer);
```

**Comment by RalphL79** [comment]
I have installed the Buffer class from npm, but for some reason the server closes the connection (makes the "will" option), any idea?

**Comment by shankerwangmiao** [comment]
I'm not quite sure. How about disabling ssl encrypt and dumping network traffic?

**Comment by RalphL79** [comment]
Yesterday I finally put it working, this is how I have done:
**server (service) side:** 
 var payload = new Buffer.from([ 0x02, 04x1, 0x01, 0x74, 0x12]);
 client.publish(topicPub, payload);
**on the web page client:**
  var buffer = new Uint8Array([0x02, 04x1, 0x01, 0x74, 0x12]);
  client.publish(topicPub, buffer);

Regarding the other problem the "will" option closing connection is an error that occurs from time to time, and I have to restart all software (like a watchdog) to connect again, sometimes the watchdog occurs 2 or 3 times before a clean an stable mqtt connection other times the watchdog doesn't occurs....
The error is something like:
MQTT_CALLBACK_SOCK_CONNECTED: -104
it seems the error is the following: ECONNRESET connection reset by peer.
I just don't understand why this error occurs from time to time, is there any workaround? Cloud be a problem of Websockets/Handshake?

**Comment by shankerwangmiao** [comment]
Maybe there are issues with the underlying network.

**Comment by RalphL79** [comment]
that's what I'm thinking, but it must something inside (at the beginning) of the mtt_connect function, this only occurs when I try to make the mqtt connection...but I can't go deeper (I have ".a" library) ...

**Pull request merged**
