### PR TITLE
chore(deps): bump readable-stream and add node 18 to ci

### PR DESCRIPTION
**Pull request by robertsLando**

### CODE REVIEW

**Comment by robertsLando** [comment]
@YoDaMa Hints about the error?

**Comment by YoDaMa** [comment]
looks like a problem with the generated browser files… async await is fine in browser tho so maybe a bad test.

**Comment by robertsLando** [comment]
Tests are 👍🏼

**Comment by robertsLando** [comment]
@YoDaMa Ping

**Review by YoDaMa — APPROVED** [review]

**Pull request merged**
