### PR TITLE
Remove a .only on a test.

### PR DESCRIPTION
**Pull request by miotabbott**
A test was singled out when developing a previous commit. Restore the unit tests to normal operation.

### CODE REVIEW

**Comment by mcollina** [comment]
The test is not passing on my box :(. Any idea?

**Comment by miotabbott** [comment]
Seems to be passing on the build machine. What sort of error do you get on your box?

**Comment by mcollina** [comment]
duplicate message on your test :/

**Comment by miotabbott** [comment]
That's no good. I will try to reproduce.

**Pull request merged**
