### PR TITLE
show example of promisification failure

### PR DESCRIPTION
**Pull request by boneskull**
as [I mentioned](https://github.com/mqttjs/MQTT.js/issues/579#issuecomment-335876893) in #579, this illustrates a problem I'm seeing with disconnection.  see the build failure

### CODE REVIEW

**Comment by RangerMauve** [comment]
I guess we should be waiting for the disconnect event before calling the callback as well,.

**Comment by boneskull** [comment]
@RangerMauve I'm suspicious about whether or not `connect()` necessarily waits a tick before emitting `connect`.

**Comment by RangerMauve** [comment]
@boneskull `connect` is emitted when we get the MQTT packet for [connack](https://github.com/mqttjs/MQTT.js/blob/master/lib/client.js#L825), since it requires a network trip it'll be guaranteed to be async.

**Comment by boneskull** [comment]
> connect is emitted when we get the MQTT packet for connack, since it requires a network trip it'll be guaranteed to be async.

that's what I'd assume, but maybe my debugger is messed up...

**Comment by boneskull** [comment]
yeah I think this is my misuse of `pify`

**Comment by boneskull** [comment]
`pify` does not mutate

**Comment by RangerMauve** [comment]
Yeah, if `connect()` in the tests is connecting to a local server, then it should be async. Don't see any way for a debugger to make it sync. We have a whole bunch of listeners for `connect` in the constructor, maybe they're interfering with each other or with the connect listener you've added in the `beforeEach`? Not sure if that makes sense, though.

Could you describe again what the problem you're seeing is? Does it time out or throw an error? Or was it that it's auto-reconnecting?

**Comment by boneskull** [comment]
the root problem was auto-reconnection, but I think that's because of naive promisification on my part.  

(also there's the case where `disconnecting` is never set to `false` once it's been `true`--likely another issue entirely with as-of-yet unknown consequences)

**Pull request closed without merging**
