### PR TITLE
Fix production vulnerability

### PR DESCRIPTION
**Pull request by LaurentGoderre**
Addresses the production packages mentioned in #1287

### CODE REVIEW

**Comment by LaurentGoderre** [comment]
SOmehwat a duplicate of #1259

**Comment by LaurentGoderre** [comment]
@mcollina

**Comment by mcollina** [comment]
@YoDaMa could you merge and release maybe?

**Comment by YoDaMa** [comment]
Yeah. I’ll get on it.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by LaurentGoderre** [comment]
Thanks @YoDaMa ! Can you let me know when a new version is releases with this fix?

**Pull request merged**
