### PR TITLE
fix: path for bin files

### PR DESCRIPTION
**Pull request by YoDaMa**
This is a fix from PR #1096 , which moved some of the CLI functionality into the bin folder. 

We need to add some form of integration testing so this doesn't happen again...

Addresses: #1106

### CODE REVIEW

**Comment by YoDaMa** [comment]
@jdiamond if you have ideas on integration tests for CLI code, I don't have knowledge in that subject.

**Comment by YoDaMa** [comment]
also should resolve https://github.com/asyncapi/website/issues/107

**Comment by jdiamond** [comment]
Maybe a test could be to use `child_process.exec` to run `node ./bin/mqtt.js` and assert that the exit code is 0?

**Comment by YoDaMa** [comment]
@jdiamond I'll add that test before I merge.

**Comment by OmgImAlexis** [comment]
@YoDaMa did you want to merge and add the test after to get this back out and working for users?

**Comment by YoDaMa** [comment]
Yeah let’s do that. I was going to get to the tests but I’ve been struggling to get anything done this week. Shit is heavy.

**Pull request merged**
