### PR TITLE
feat: custom websocket support

### PR DESCRIPTION
**Pull request by helios57**
We need to add special protocols to connect to our mqtt broker over websocket. With this small addition (which hopefully helps others as well) we can do it very easy. Otherwhise we need to build our own streamBuilder and copy alot code.

### CODE REVIEW

**Review by robertsLando — CHANGES_REQUESTED** [review]
Please add a unit test that covers this feature and also mention it in docs

**Comment by helios57** [comment]
Thanks for the fast reply, unfortenately I am not able to run the test on windows and installing everyting on linux took me to long.
I tried to add some tests and can also update the doc but as long as I cant run the tests it's pretty useless and I can't add better tests.

The error seems to be known but I could not find a working solution:
> node_modules/.bin/nyc --reporter=lcov --reporter=text ./node_modules/mocha/bin/_mocha -r ts-node/register test/*.ts --exit

Der Befehl "node_modules" ist entweder falsch geschrieben oder
konnte nicht gefunden werden.

**Comment by helios57** [comment]
Just found something working:
If I change this line it seems to run:
 "unit-test:node": "nyc --reporter=lcov --reporter=text ./node_modules/mocha/bin/_mocha -r ts-node/register test/*.ts --exit",

I will add more tests and update the docu.

**Comment by helios57** [comment]
Thanks for the fast response. Unittest is now added and the docs should be updated.

**Review by robertsLando — APPROVED** [review]

**Pull request merged**
