### PR TITLE
Align OnConnectCallback with specs expecting Connack packet

### PR DESCRIPTION
**Pull request by ccarcaci**
- Related issue: https://github.com/mqttjs/MQTT.js/issues/1321.
- (unrelated but blocking) Set noImplicitAny to false in test/typescript/tsconfig.json due to a compilation error resolving ws types.
Compilation error was:
```
$ npm run typescript-compile-test

> mqtt@4.2.8 typescript-compile-test
> tsc -p test/typescript/tsconfig.json

types/lib/client-options.d.ts:3:23 - error TS7016: Could not find a declaration file for module 'ws'. '/home/ccarcaci/git/MQTT.js/node_modules/ws/index.js' implicitly has an 'any' type.
  Try `npm install @types/ws` if it exists or add a new declaration (.d.ts) file containing `declare module 'ws';`

3 import WebSocket from 'ws'
                        ~~~~


Found 1 error.
```
- OnConnectCallback receives back a Connack packet as stated in the MQTT specs.
- Not sure which kind of release version to associate with this PR. Major is suggested because of interface change that is not backward compatible for the ones are using typescript.

### CODE REVIEW

**Comment by YoDaMa** [comment]
@ccarcaci could you add `@types/ws` to the dev dependencies of the package and then remove the changes to tsconfig

**Comment by ccarcaci** [comment]
> looks good pending reverting tsconfig adjustments

Done.

**Comment by YoDaMa** [comment]
lgtm

**Review by YoDaMa — APPROVED** [review]

**Comment by YoDaMa** [comment]
thank you @ccarcaci for your contribution :)

**Comment by ccarcaci** [comment]
> thank you @ccarcaci for your contribution :)

My pleasure :)

**Pull request merged**
