### PR TITLE
tslint should be run on pre-commit

### PR DESCRIPTION
**Pull request by yohei1126**
This should avoid some mistakes of coding styles on TypeScript definitions.

### CODE REVIEW

**Comment by mcollina** [comment]
I think we should also run it on travis, would you mind updating?

**Comment by yohei1126** [comment]
Yes, please go ahead.

**Comment by ogis-onishi** [comment]
Is `npm run tslint` already included in CI on travis?
https://github.com/mqttjs/MQTT.js/blob/master/package.json#L30

**Comment by mcollina** [comment]
oh yes. Ok, merging.

**Pull request merged**
