### PR TITLE
Adding bower.json file to add to bower registry

### PR DESCRIPTION
**Pull request by ccravens**
It would be great for this package to be available via bower. This addition provides the required bower.json file, and the project can be registered on bower via "bower register mqtt https://github.com/mqttjs/MQTT.js"

### CODE REVIEW

**Comment by RangerMauve** [comment]
Doesn't bower require the code to be built into something other than CommonJS?

**Comment by mcollina** [comment]
Yes it does. I'm not fan of committing a built package to the repo, but I see it might be helpful for the bower community. Any other opinion?

**Comment by sandro-k** [comment]
From my perspective 
> Bower  - A package manager for the web 

is a package is something that runs in the Browser or similar like Chrome Packaged Apps and therefor should include a bundled version of MQTT.js for the Browser. Publishing MQTT.js to Bower like this does not benefit over `npm install --save-dev mqtt` and then bundle it yourself. What would be your benefit of publishing `MQTT.js` to Bower?

**Comment by ccravens** [comment]
Most JavaScript libraries are available via bower and a lot of projects use bower to separate front end dependencies from NPM for Node (server side) dependencies. There is nothing stopping someone from using NPM for mqtt.js, but it would be a nice to have for people that use bower. In my case I leverage Mqtt.js and Mosca extensively, and Mqtt.js is the only project I have to fetch from node_modules rather than bower.

**Comment by mcollina** [comment]
@ccravens the problem with this setup is that it will not work. You need a browserified thing rather than the common js module.

**Comment by sandro-k** [comment]
Bower allows to run a `postinstall script` that we can use to bundle MQTT.js for the Browser and avoid to publish it via Git.

**Comment by mcollina** [comment]
Any updates on this? Feel free to reopen with a way to bundle `mqtt.js` with browserify.

**Pull request closed without merging**
