### PR TITLE
chore: bump mqtt-packet@8.1.1

### PR DESCRIPTION
**Pull request by robertsLando**
Reproduce failing test: 

```
npx mocha -g "should not resubscribe when reconnecting if suback is error" test/client.js
```

Seems the same happens with mqtt-packet@7

Error

```
 1) MqttClient
       auto reconnect
         should not resubscribe when reconnecting if suback is error:
     Error: Timeout of 2000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (MQTT.js/test/client.js)
      at listOnTimeout (node:internal/timers:557:17)
      at processTimers (node:internal/timers:500:7)
```

@YoDaMa any hints?

### CODE REVIEW

**Comment by robertsLando** [comment]
Bug is caused by a wrong suback validation in mqtt-packet 7.0.0 https://github.com/mqttjs/mqtt-packet/pull/134

**Comment by robertsLando** [comment]
@YoDaMa Tests are ok now 🎉

**Comment by robertsLando** [comment]
@YoDaMa Ping

**Comment by robertsLando** [comment]
Fixed conflicts

**Comment by robertsLando** [comment]
@mcollina Who should maintain this library? Seems no one is checking PRs...

**Comment by mcollina** [comment]
In theory @YoDaMa.

**Comment by robertsLando** [comment]
@YoDaMa I reached you via email, any news about that?

**Comment by robertsLando** [comment]
@vishnureddy17 @ryanwinter @BertKleewein anyone here that can kindly merge this PR?

**Review by vishnureddy17 — APPROVED** [review]

**Comment by robertsLando** [comment]
@vishnureddy17 I already spoke with @mcollina long time ago about this and he told me to ask to @YoDaMa , so I reached out him privately and after two months he answered that he had some personal problems but that he would have added me ASAP (this happened almost a year ago now). 

Matteo knows me, I'm a maintainer of [Aedes MQTT broker](https://github.com/moscajs/aedes) (created by him) so quite sure he would not be against this.

I also would like to know how your actual release process work right now, if that is manual or what else

**Comment by vishnureddy17** [comment]
@robertsLando Thanks for that context. I just added you as a maintainer. I just sent you an e-mail, could you take a look? Thanks!

**Comment by robertsLando** [comment]
Answered. Thanks!

**Pull request merged**
