### PR TITLE
Parse messages to the mqtt pub cli as strings.

### PR DESCRIPTION
**Pull request by mcollina**
This should be an easy fix, but please review anyway.

Also @yangpu can you please check if this solves your issue?

### CODE REVIEW

**Comment by yangpu** [comment]
No, the bug is still existing.

**Comment by mcollina** [comment]
It is working in this branch, have you checked it out?

**Comment by mcollina** [comment]
Anyone else can try and confirm?

**Comment by yangpu** [comment]
I have tried several times after check out the branch, but the issue is still there.

**Comment by mcollina** [comment]
Can you please try it again? Should be working now.

**Comment by yangpu** [comment]
great, it works now!

**Pull request merged**
