### PR TITLE
Fix for issue #209: Change PUBACK for QOS 1 to be on callback from handleMessage

### PR DESCRIPTION
**Pull request by willshulstad**
Fixed issue #209  where puback was sent before processing was complete for QOS 1.

### CODE REVIEW

**Comment by jdiamond** [comment]
Thanks for this!

You don't think it should automatically disconnect when the `handleMessage` callback receives an error?

**Comment by willshulstad** [comment]
I don't think that the error itself should cause a disconnect internally in the client.  The only time that handleMessage will return an error is if the specific implementation has error checking logic in the handleMessage method.  If we leave the disconnect logic up to the specific implementation, then the implementor can decide if a disconnect is necessary or not.  

The use case we have is that we are using the client to watch for messages on the broker and storing them to our DB using rest services.  If those rest services are down, we don't want to ack the message because our client is very lightweight and does not persist anything to disk internally.  We rely on the broker to own the message until we have successfully sent the message on to our rest services.  

In the case that the rest services are temporarily down, we would not disconnect the client from the broker, we would just wait for the broker to resend the message and hope that the rest services are up by then.  If however, we had a different issue (internal exception, multiple sequential failures, etc.) then we would decide to disconnect from the broker.

**Comment by mcollina** [comment]
@willshulstad I do not think this PR is correct. Specifically:

>  In the QoS 1 delivery protocol, the Receiver MUST respond with a PUBACK Packet containing the Packet Identifier from the incoming PUBLISH Packet, having accepted ownership of the Application Message (Section 4.3.2).

The important part for this PR is "accepted ownership", which I think it is about reception, **not** having successfully processed the message.

**Comment by willshulstad** [comment]
@mcollina 
The problem with that interpretation is the client does not inherently handle persistence.  Since the application that is implementing handleMessage will be handling persistence, it should be allowed to decide on whether to accept ownership.  I don't think "accepting ownership" is simply about receiving, but about accepting responsibility for the message.

The way you describe "accepting ownership" actually sounds more like what is expected for QOS 0, rather than QOS 1:

> In the QoS 0 delivery protocol, the Receiver Accepts ownership of the message when it receives the PUBLISH packet.

As it stands today, if the application has any issue persisting the message, the ACK will already have been sent and the broker will have removed the message.  At that point, the message will be lost forever.  That makes this client unusable for any application that requires message delivery integrity.

**Comment by RangerMauve** [comment]
@willshulstad AFAIK MQTT.js does persistence via [a store](https://github.com/mqttjs/MQTT.js#store). If that isn't working for your use case, you could implement a custom store that integrates with your application.

**Comment by willshulstad** [comment]
@RangerMauve I may be reading the code wrong, but it does not look like the message store is used for incoming messages with QOS 1.  The store seems to be used for outgoing messages (to handle the PUBACK from the broker) and QOS 2 (to handle the PUBREL from the broker).

**Comment by kerber** [comment]
I agree with Will that it would be great to be able to have the implementation control whether it takes responsibility for the received message. In the event of an error in my client, I'd rather trust a broker to keep the data safe than I would my own implementation of a data store. This would also mean that I would have to make sure my data store is performant and truly durable.

**Comment by mcollina** [comment]
There is `incomingStore` for that https://github.com/mqttjs/MQTT.js/blob/master/lib/client.js#L87.
Specifically, `incomingStore` is used for QoS 2 packets: https://github.com/mqttjs/MQTT.js/blob/master/lib/client.js#L802-L804.

> I agree with Will that it would be great to be able to have the implementation control whether it takes responsibility for the received message. In the event of an error in my client, I'd rather trust a broker to keep the data safe than I would my own implementation of a data store. This would also mean that I would have to make sure my data store is performant and truly durable.

I am not 100% convinced about this. Let's make the case that the broker has a "botched" message in the queue to be sent, one that will crash the client on receipt. With the current approach, the client will crash and likely restart. However, with the approach you are suggesting, the client would continue to crash, because the message is never removed from the broker queue.

**Comment by kerber** [comment]
Correct me if I'm wrong, but it doesn't appear that the `incomingStore` handles recovery from any sort of failure, rather it is just responsible for keeping track for the QOS2 publish exchange. It doesn't actually help ensure that QOS1 or QOS2 messages are persisted once the client takes ownership and responsibility of the message. Further, there's no actual mechanism in this library to protect the messages it owns in the event of a server or application failure.

In any sort of serious application that I can think of, it would be preferable to have the implementation handle malformed packets, rather than just dumping data. Data integrity, I would think, is higher priority than handling bad messages, as the former is explicitly covered in the spec and the latter is an implementation detail.

**Comment by mcollina** [comment]
> Correct me if I'm wrong, but it doesn't appear that the incomingStore handles recovery from any sort of failure, rather it is just responsible for keeping track for the QOS2 publish exchange. It doesn't actually help ensure that QOS1 or QOS2 messages are persisted once the client takes ownership and responsibility of the message. Further, there's no actual mechanism in this library to protect the messages it owns in the event of a server or application failure.

Definitely. You are probably looking for a different type of library or even protocol, with a different design choices. MQTT is a protocol is build for device -> broker communication, not a server <-> server protocol.

> In any sort of serious application that I can think of, it would be preferable to have the implementation handle malformed packets, rather than just dumping data. Data integrity, I would think, is higher priority than handling bad messages, as the former is explicitly covered in the spec and the latter is an implementation detail.

In fact, it's quite the opposite. MQTT is a protocol to be deployed in the field, and a supreme imperative is to keep working, even if there is some form of "panic". A malformed message in the the queue to the client can make a client crash over and over again at each reconnect.
I have seen this in real-life several time, and a lost message is always better in IoT systems.

From the spec:

> The receiver is not required to complete delivery of the Application Message before sending the PUBACK. When its original sender receives the PUBACK packet, ownership of the Application Message is transferred to the receiver.

Our current failure model is "if it crashes it crashes", and every data that is "in flight" is lost.

**Comment by jdiamond** [comment]
@mcollina: I think you see MQTT.js as the "receiver" in the spec. To me, MQTT.js is just a library and my applications are the receivers and, therefore, should have the ability to decide when they accept ownership of a message.

I agree with you that not sending a PUBACK violates the spec, but sending it without giving the application any say feels too presumptuous to me. Should it at least be able to end the connection instead of sending a PUBACK?

I think overriding `handleMessage` is an advanced use case that only experienced developers should be doing and we should document it with appropriate warnings that the connection should really be terminated if it can't call back without an error. But having it gives others the ability to experiment with use cases that might be different from the ones we have experience with.

**Comment by mcollina** [comment]
Closing for no activity, feel free to reopen!

**Pull request closed without merging**
