### PR TITLE
Added MQTT 5 properties object to publish options

### PR DESCRIPTION
**Pull request by koopman-mark**

### CODE REVIEW

**Comment by koopman-mark** [comment]
Addresses issue #1074

**Comment by aemaem** [comment]
Is this PR just hanging because of the 10.x build?

**Comment by Global-Ekons** [comment]
Its hanging because it is missing its system32 folder.

**Comment by Global-Ekons** [comment]
Error 104

The system32 folder is mia, now it doesn't matter what I try, won't even
reinstall win10, as it doesn't pass Boot.

Boot option doesn't work either, or any other command doesn't work either.


LAPTOP, DELL LATITUDE E6540, 64bit with 16gb ram.
Win10 System was never reinstalled after 2016, as updates did enough, was
though a Win8.1 beforehand.

**Comment by highcaliberkevin** [comment]
I am trying to use the `.publish(...)` method's `responseTopic` and a Mosquitto broker (which has v5 support). I would absolutely love for this to be merged--is there anything that can be done (perhaps I can assist? testing, et al) to get it in there? Thanks!

**Pull request merged**
