### PR TITLE
Added packet type (cmd) for existing replace test for store.

### PR DESCRIPTION
**Pull request by redboltz**
Removed duplicated test.

### CODE REVIEW

**Comment by redboltz** [comment]
Please see https://github.com/mqttjs/MQTT.js/pull/859#issuecomment-415970423

**Comment by redboltz** [comment]
Thank you for merging. After the new version is released, I will send the PR for mqtt-level-store to support publish order. It requires the new MQTT.js release for `npm install`.

**Comment by mcollina** [comment]
It's already published, 2.18.6.

**Comment by mcollina** [comment]
Or do you need this as well?

**Comment by redboltz** [comment]
https://github.com/mqttjs/MQTT.js/releases/tag/v2.18.6

released this 9 hours ago · 2 commits to master since this rele

It seems that the release v2.18.6 (tag v2.18.6) does not contain #860.

https://github.com/mqttjs/MQTT.js/commits/v2.18.6

And mqtt-level-store's package.json gets the latest release **but not master** from npm when I execute `npm install`. https://www.npmjs.com/package/mqtt

So I need the release that contains #860.

**Comment by redboltz** [comment]
mqtt-level-store's test includes mqtt.js's abstract_store test in node_modules.

https://github.com/mcollina/mqtt-level-store/blob/master/test.js#L5

**Comment by mcollina** [comment]
Done.

**Comment by redboltz** [comment]
Thank you! I send https://github.com/mcollina/mqtt-level-store/pull/11

**Pull request merged**
